### PR TITLE
Fixed test_analysis.py

### LINKED ISSUE #57: Import errors in tra_analysis unit tests
**Describe the bug**
There are improper imports in the unit test script for tra_analysis.

**To Reproduce**
1. Run `python test_analysis.py`

**Expected behavior**
Expected behavior is for the unit test to run.

### PR DESCRIPTION
**Pull request by zpan1**
Fixed import statements and module names to match new submodules.
Also added the missing numpy import in Sort.py

Fixes #57

### CODE REVIEW

**Comment by ltcptgeneral** [comment]
Please remember to link the issue on the right hand side, request reviewers, and go ahead and add yourself to __authors__ in the init.py and Sort.py. Also please apply labels as appropriate.

**Review by ltcptgeneral — APPROVED** [review]
Verified changes to be working, LGTM

**Review by devksingh4 — APPROVED** [review]
lgtm

**Comment by ltcptgeneral** [comment]
closes #57

**Pull request merged**
